<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\externals\TedToolkit\props\NugetPackage.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
    <PackageReference Include="System.Text.Encoding.CodePages" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TedToolkit.Step21.IntegrationTests" />
    <InternalsVisibleTo Include="TedToolkit.Step21.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.Step21.Analyzer.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\Antlr4.Runtime.Standard.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.RoslynHelper.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\System.Memory.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\ZString.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

</Project>
