<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TedToolkit.Step21.IntegrationTests" />
    <InternalsVisibleTo Include="TedToolkit.Step21.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.Step21.Analyzer.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\Antlr4.Runtime.Standard.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\TedToolkit.RoslynHelper.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\System.Memory.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\TedToolkit.Step21.Analyzer\bin\$(Configuration)\netstandard2.0\ZString.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

</Project>
