// -----------------------------------------------------------------------
// <copyright file="ExpressIncrementalGenerator.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;

using TedToolkit.Step21.Analyzer.Express.Binding;

namespace TedToolkit.Step21.Analyzer.Generation;

/// <summary>
/// Generates deterministic C# artifacts from the closed set of supplied EXPRESS additional files.
/// </summary>
[Generator]
[CLSCompliant(false)]
public sealed class ExpressIncrementalGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers the EXPRESS AdditionalFiles compilation and source-emission pipeline.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var generatorInputs = context.AdditionalTextsProvider
            .Where(static input => IsGeneratorInput(input.Path));
        var expressInputs = context.AdditionalTextsProvider
            .Where(static input => IsGeneratorInput(input.Path))
            .Select(static (input, cancellationToken) => new ExpressGeneratorInput(
                input.Path,
                input.GetText(cancellationToken)?.ToString()))
            .Collect()
            .Select(static (inputs, _) => Compile(inputs));

        context.RegisterSourceOutput(expressInputs, static (productionContext, result) =>
        {
            var plan = ExpressGenerationPlan.Create(result.Compilation, result.Inputs);
            ExpressSourceEmissionStage.Emit(productionContext, result, plan);
        });

        var compatibilitySource = context.CompilationProvider
            .Combine(generatorInputs.Collect())
            .Select(static (input, _) => input.Right.Any(static item =>
                    string.Equals(Path.GetExtension(item.Path), ".exp", StringComparison.OrdinalIgnoreCase))
                ? CreateCodeAnalysisCompatibilitySource(input.Left)
                : "");
        context.RegisterSourceOutput(compatibilitySource, static (productionContext, source) =>
        {
            if (source.Length == 0)
            {
                return;
            }

            productionContext.AddSource("Step21CodeAnalysisAttributes.g.cs", source);
        });
    }

    private static string CreateCodeAnalysisCompatibilitySource(Compilation compilation)
    {
        var declarations = new StringBuilder();
        AppendParameterlessAttribute(
            declarations,
            compilation,
            "NotNullAttribute",
            "global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | "
                + "global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue");
        AppendParameterlessAttribute(
            declarations,
            compilation,
            "MaybeNullAttribute",
            "global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | "
                + "global::System.AttributeTargets.Property | global::System.AttributeTargets.ReturnValue");
        AppendParameterlessAttribute(
            declarations,
            compilation,
            "AllowNullAttribute",
            "global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | "
                + "global::System.AttributeTargets.Property");
        AppendParameterlessAttribute(
            declarations,
            compilation,
            "DisallowNullAttribute",
            "global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter | "
                + "global::System.AttributeTargets.Property");
        AppendBooleanAttribute(declarations, compilation, "NotNullWhenAttribute");
        AppendBooleanAttribute(declarations, compilation, "MaybeNullWhenAttribute");
        if (declarations.Length == 0)
        {
            return "";
        }

        return "// <auto-generated />\n"
            + "namespace System.Diagnostics.CodeAnalysis\n"
            + "{\n"
            + declarations
            + "}\n";
    }

    private static void AppendParameterlessAttribute(
        StringBuilder declarations,
        Compilation compilation,
        string typeName,
        string targets)
    {
        if (HasUsableCodeAnalysisAttribute(compilation, typeName))
        {
            return;
        }

        declarations.Append("    [global::System.AttributeUsage(")
            .Append(targets)
            .AppendLine(", Inherited = false)]")
            .Append("    internal sealed class ")
            .Append(typeName)
            .AppendLine(" : global::System.Attribute")
            .AppendLine("    {")
            .AppendLine("    }")
            .AppendLine();
    }

    private static void AppendBooleanAttribute(
        StringBuilder declarations,
        Compilation compilation,
        string typeName)
    {
        if (HasUsableCodeAnalysisAttribute(compilation, typeName))
        {
            return;
        }

        declarations.AppendLine(
                "    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]")
            .Append("    internal sealed class ")
            .Append(typeName)
            .AppendLine(" : global::System.Attribute")
            .AppendLine("    {")
            .Append("        public ")
            .Append(typeName)
            .AppendLine("(bool returnValue)")
            .AppendLine("        {")
            .AppendLine("            ReturnValue = returnValue;")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        public bool ReturnValue { get; }")
            .AppendLine("    }")
            .AppendLine();
    }

    private static bool HasUsableCodeAnalysisAttribute(Compilation compilation, string typeName)
    {
        var type = compilation.GetTypeByMetadataName("System.Diagnostics.CodeAnalysis." + typeName);
        return type is not null
            && (type.DeclaredAccessibility == Accessibility.Public
                || SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, compilation.Assembly));
    }

    private static ExpressGeneratorCompilation Compile(in ImmutableArray<ExpressGeneratorInput> inputs)
    {
        var readableInputs = inputs
            .Where(input => input.Text is not null
                && string.Equals(Path.GetExtension(input.Path), ".exp", StringComparison.OrdinalIgnoreCase))
            .Select(input => new ExpressSchemaSource(input.Path, input.Text!));
        return new(inputs, ExpressSchemaCompiler.Analyze(readableInputs));
    }

    private static bool IsGeneratorInput(string path)
    {
        var extension = Path.GetExtension(path);
        return string.Equals(extension, ".exp", StringComparison.OrdinalIgnoreCase)
            || string.Equals(extension, ".p21map", StringComparison.OrdinalIgnoreCase);
    }
}